### ISSUE TITLE
update npm artifact

### ISSUE THREAD

**Issue by frank06** [bentomas/node-async-testing#2]
I'm trying it out... great library so far. There are many features mentioned in the website (like `wrap`) that are not available on npm (i did `npm install async_testing@latest`, which gave me 0.3.2).

Would it be possible that you pushed these to npm?

**Comment by bentomas** [comment]
Hey, sorry about the confusion, the website (bentomas.github.com/node-async-testing) is for the next version (0.4.0) of node-async-testing that I am hoping to push out in the next week.  I'm still working on doing some more testing and am waiting for feedback from people using the release candidate.  If you want to use the new features you're going to have to use trunk until then.

In the mean time the old README is the only source of documentation:  https://github.com/bentomas/node-async-testing/blob/b693748e6531a208993836c5597779ca9dfd9f13/README.md

I'll push that README back to master and remove the link to the website until I officially push the new version.

Sorry if this caused you any problems!

**Comment by bentomas** [comment]
Done!

**Comment by frank06** [comment]
Ok, no problem, perhaps for clarity's sake it'd be good to inform that `npm install async_testing` won't get you the features in the current documentation.

I got the bleeding edge version from master. Still trying it out.
