### ISSUE TITLE
Great Project, but the npm is a little bit outtodate

### ISSUE THREAD

**Issue by Calamari** [bentomas/node-async-testing#8]
On git there is version 0.4 but the npm has only 0.3.1 available, That was a bit irritating, because the readme is out to date, too.

**Comment by bentomas** [comment]
See the first comment here:

https://github.com/bentomas/node-async-testing/issues/closed#issue/2

I haven't officially pushed out the 4th version because it still has some bugs.  And I've been too busy to work on it.  Sorry!

Patches accepted!
